export const InputTypesForInputBoxes: Record<string, string> = {
  TC: "tc",
  "Doğum Tarihi": "date",
  "Telefon Numarası": "phone",
  "Araç Yeni tescil mi": "text",
  "Araç Plakası": "plate",
  "Tescil Belge Seri No": "text",
  "Boy (cm)": "height",
  "Kilo (kg)": "weight",
  "Sigortalı Sayısı": "selectNumber",
  "Sigortalıların Doğum Tarihi": "date",
  "Sigortalıların Cinsiyeti": "selectGender",
  "Sigortalıların Yakınlık Derecesi (Eş / Çocuk / Anne / Baba / Kardeş)":
    "text",
  "Konutun Açık Adres Bilgisi": "text",
  "Konutun Yapım Yılı": "year",
  "Konutun Bulunduğu Kat": "number",
  "Konutun Bulunduğu Kat Sayısı": "number",
  "Kiracı mısınız, mülk sahibi misiniz?": "text",
  "DASK Sigortası Yaptırılmış mı?": "booleanyn",
  "Konut Türü (Apartman / Müstakil Ev / Villa / Dubleks / Tripleks)": "text",
  "Konutun Brüt Metrekare Bilgisi": "number",
  "Binanın Yapı Tipi (Betonarme / Ahşap / Çelik)": "text",
  "Konutun Boş Kalma Süresi (Ay)": "number",
  "Konutun Kullanım Amacı (Mesken / İşyeri / İkametgah / Depo)": "text",
  "Konutun Sigorta Bedeli": "number",
  "Konutun İçindeki Eşyaların Sigorta Bedeli": "number",
  "Seyahat Başlangıç Tarihi": "date",
  "Seyahat Bitiş Tarihi": "date",
  "Seyahat Edilecek Ülke": "countrySelect",
  "Pasaport Numarası": "passportNumber",
  "Seyahat Amacı (Tatil / İş / Tedavi / Eğitim)": "text",
  "İşyerinin Açık Adres Bilgisi": "text",
  "İşyerinin Bulunduğu Kat": "number",
  "İşyerinin yapım yılı": "number",
  "İşyerinin bulunduğu bina yapı tipi (Betonarme / Ahşap / Çelik)": "text",
  "İşyerinin bulunduğu binanın kat sayısı": "number",
  "Kiracı mısınız, mülk sahibi misiniz": "text",
  "Faaliyet konusu": "text",
  "İşyerinin bulunduğu bina sigorta bedeli": "number",
  "İşyerinin bulunduğu bina içindeki emtia/demirbaş sigorta bedeli": "number",
  "Bina içindeki makine ve tesisat sigorta bedeli": "number",
  "Faiz Oranı": "number",
  "Kredi Tutarı": "number",
  "Kredi Vadesi": "number",
  "Meslek Grubu": "text",
  "Çalıştığı Kurum": "text",
  "Mesleki Sorumluluk Sigortası Yaptırılacak Kişi Sayısı": "number",
};
