export const InputTypesForInputBoxes: Record<string, string> = {
  TC: "tc",
  "Doğum Tarihi": "date",
  "Telefon Numarası": "phone",
  "Araç Yeni tescil mi": "multiselectyn",
  "Araç Plakası": "plate",
  "Tescil Belge Seri No": "text",
  "Boy (cm)": "height",
  "Kilo (kg)": "weight",
  "Sigortalı Sayısı": "selectNumber",
  "Sigortalıların Doğum Tarihi": "date",
  "Sigortalıların Cinsiyeti": "multiSelectGender",
  "Sigortalıların Yakınlık Derecesi (Eş / Çocuk / Anne / Baba / Kardeş)":
    "multiSelectFamily",
  "Konutun Açık Adres Bilgisi": "text",
  "Konutun Yapım Yılı": "year",
  "Konutun Bulunduğu Kat": "selectNumber",
  "Konutun Bulunduğu Kat Sayısı": "selectNumber",
  "Kiracı mısınız, mülk sahibi misiniz?": "multiSelectTenant",
  "DASK Sigortası Yaptırılmış mı?": "multiselectyn",
  "Konut Türü (Apartman / Müstakil Ev / Villa / Dubleks / Tripleks)":
    "multiselectHomeType",
  "Konutun Brüt Metrekare Bilgisi": "selectNumber",
  "Binanın Yapı Tipi (Betonarme / Ahşap / Çelik)": "multiSelectBuildingType",
  "Konutun Boş Kalma Süresi (Ay)": "selectNumber",
  "Konutun Kullanım Amacı (Mesken / İşyeri / İkametgah / Depo)":
    "multiSelectHomeUsage",
  "Konutun Sigorta Bedeli": "selectNumber",
  "Konutun İçindeki Eşyaların Sigorta Bedeli": "selectNumber",
  "Seyahat Başlangıç Tarihi": "date",
  "Seyahat Bitiş Tarihi": "date",
  "Seyahat Edilecek Ülke": "countrySelect",
  "Pasaport Numarası": "passportNumber",
  "Seyahat Amacı (Tatil / İş / Tedavi / Eğitim)": "multiSelectTravelPurpose",
  "İşyerinin Açık Adres Bilgisi": "text",
  "İşyerinin Bulunduğu Kat": "number",
  "İşyerinin yapım yılı": "number",
  "İşyerinin bulunduğu bina yapı tipi (Betonarme / Ahşap / Çelik)": "text",
  "İşyerinin bulunduğu binanın kat sayısı": "number",
  "Kiracı mısınız, mülk sahibi misiniz": "text",
  "Faaliyet konusu": "text",
  "İşyerinin bulunduğu bina sigorta bedeli": "number",
  "İşyerinin bulunduğu bina içindeki emtia/demirbaş sigorta bedeli": "number",
  "Bina içindeki makine ve tesisat sigorta bedeli": "number",
  "Faiz Oranı": "percentage",
  "Kredi Tutarı": "number",
  "Kredi Vadesi": "number",
  "Meslek Grubu": "text",
  "Çalıştığı Kurum": "text",
  "Mesleki Sorumluluk Sigortası Yaptırılacak Kişi Sayısı": "selectNumber",
};
